<a href="https://colab.research.google.com/github/eshwardora/214513-Python-/blob/main/CIE_3_214513.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Ex1


In [ ]:
import numpy as np

Ex2

In [ ]:
print(np.__version__)
np.show_config()

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

Ex3

In [ ]:
Z = np.zeros(10)
print(Z)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Ex4

In [ ]:
import numpy
numpy.info(numpy.add) 

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

Ex5

In [ ]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Ex6

In [ ]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Ex7

In [ ]:
Z = np.arange(50)
Z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

Ex8

In [ ]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Ex9

In [ ]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


Ex10

In [ ]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Ex11

In [ ]:
import numpy as np
Z = np.random.random((3,3,3))
print(Z)

[[[0.46205361 0.28782502 0.93684932]
  [0.06826732 0.27295213 0.56644411]
  [0.95879106 0.03490674 0.93943481]]

 [[0.6810964  0.90182157 0.16460073]
  [0.57150916 0.08948605 0.38082358]
  [0.02110085 0.53375475 0.50264755]]

 [[0.25599197 0.16558493 0.10840826]
  [0.92707387 0.53644923 0.86575818]
  [0.77565665 0.19400936 0.26582868]]]


Ex12

In [ ]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)


0.04464432203219337 0.9918723512748555


Ex13

In [ ]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.4867859095298383


Ex14

In [ ]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0

Ex15

In [ ]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

False

Ex16

In [ ]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


Ex17

In [ ]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Ex18

In [ ]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


Ex19

In [ ]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Ex20

In [ ]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[0.72033542 1.         0.44261364 0.84860939 0.43580394]
 [0.65306117 0.01720415 0.948376   0.19226566 0.22727487]
 [0.98949914 0.23468748 0.86958653 0.40847597 0.39467879]
 [0.04171453 0.         0.04884498 0.17455101 0.77499214]
 [0.54427044 0.37669172 0.03087502 0.71366047 0.76215081]]


Ex21

In [ ]:
color = np.dtype([("r", np.ubyte, 1),
("g", np.ubyte, 1),
("b", np.ubyte, 1),
("a", np.ubyte, 1)])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


Ex22

In [ ]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


Ex23

In [1]:
import numpy as np
Z = np.arange(11) 
Z[(3 < Z) & (Z <= 8)] *= -1 
print(Z)


[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


Ex24

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


Ex25

In [2]:
Z=int(input("enter the number"))
Z**Z 
2 << Z >> 2 
Z <- Z 
1j*Z 
Z/1/1 
Z<Z>Z 


enter the number5


False

Ex26

In [3]:
np.array(0) // np.array(0) 
np.array(0) // np.array(0.) 
np.array(0) / np.array(0) 
np.array(0) / np.array(0.) 


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in floor_divide
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in true_divide
  after removing the cwd from sys.path.


nan

Ex27

In [4]:
Z = np.random.uniform(-10,+10,10) 
print (np.trunc(Z + np.copysign(0.5, Z))) 


[-5.  7. -2. -6. -0. -1.  6.  9.  4. -6.]


Ex28

In [5]:
Z = np.random.uniform(0,10,10) 
print (Z - Z%1) 
print (np.floor(Z)) 
print (np.ceil(Z)-1)


[5. 2. 2. 2. 1. 3. 4. 8. 5. 5.]
[5. 2. 2. 2. 1. 3. 4. 8. 5. 5.]
[5. 2. 2. 2. 1. 3. 4. 8. 5. 5.]


Ex29

In [6]:
Z = np.zeros((5,5)) 
Z += np.arange(5) 
print(Z) 


[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


Ex31

In [7]:
import numpy as np
Z = np.linspace(0,1,12,endpoint=True)[1:-1] 
print(Z) 


[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]
